; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps = 
	; Forzamos las dos librerías asíncronas correctas para ESP32
    https://github.com/mathieucarbou/AsyncTCP.git @ ^3.2.4
    https://github.com/mathieucarbou/ESPAsyncWebServer.git @ ^3.3.11
	s00500/ESPUI@2.2.1
	adafruit/Adafruit GFX Library@1.10.12
	dmkishi/Dusk2Dawn@^1.0.1
	https://github.com/markruys/arduino-Max72xxPanel.git
	https://github.com/PaulStoffregen/Time.git
	mathertel/RotaryEncoder@1.5.3
